sudo: require
language: node_js
node_js:
  - 10.16.3
dist: trusty
services:
  - docker
cache:
  directories:
    - client/node_modules
    - server/node_modules
    - worker/node_modules
before_install:
  - docker build -t lumframedse/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run lumframedse/react-test npm test -- --watchAll=false

after_success:
  - docker build -t lumframedse/multi-client ./client
  - docker build -t lumframedse/multi-worker ./worker
  - docker build -t lumframedse/multi-server ./server
  - docker build -t lumframedse/multi-nginx ./nginx
  # Login to the docker
  - echo ${DOCKER_PASSWRD} | docker login -u "$DOCKER_ID" --password-stdin
  # Take all the built images and push to docker hub
  - docker push lumframedse/multi-client
  - docker push lumframedse/multi-worker
  - docker push lumframedse/multi-server
  - docker push lumframedse/multi-nginx 



